name: verificación

on: 
    schedule:
      - cron:  '7 1 * * *'

defaults:
  run:
    working-directory: ./src/verificacion

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm run test
